<?php
    $chatStatuses = $block->getChatStatuses();
?>
<div id="chat-admin-container">
    <div class="user-list-wrapper">
        <div class="chats-info">
            <p><?= $escaper->escapeHtml(__('My Chats')) ?></p>
            <p><?= $escaper->escapeHtml(__('Total Chats:')) ?> <span class="total-chats"></span></p>
        </div>
        <div class="user-list">
            <!-- List of users goes here -->
        </div>
    </div>
    <h1 class="welcome-message" style="display: none;"></h1>
    <div class="chat-area">
        <div class="chat-header">
            <!-- <h2><?= $escaper->escapeHtml(__('Chat with')) ?><span class="user-name"></span></h2> -->
            <div class="left-info">
                <div class="chat-customer">
                    <span class="title"><?= $escaper->escapeHtml(__('User:')) ?></span>
                    <span class="customer"></span>
                </div>
                <div class="chat-customer">
                    <span class="title"><?= $escaper->escapeHtml(__('Email:')) ?></span>
                    <span class="email"></span>
                </div>
            </div>
            <div class="right-info">
                <div class="chat-date">
                    <span class="title"><?= $escaper->escapeHtml(__('Created at:')) ?></span>
                    <span class="date"></span>
                </div>
                <div class="chat-status">
                    <span class="title"><?= $escaper->escapeHtml(__('Status:')) ?></span>
                    <div id="status-update">
                        <select id="chat-status-list">
                            <?php foreach ($chatStatuses as $status): ?>
                                <option 
                                    value="<?= $escaper->escapeHtml($status['value']) ?>">
                                    <?= $escaper->escapeHtml($status['label']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="chat-messages">
            <!-- Messages between selected user go here -->
        </div>
        <div class="chat-input">
            <div class="textarea-wrapper">
                <textarea placeholder="<?= $escaper->escapeHtml(__('Type your message...')) ?>"></textarea>
                <button><?= $escaper->escapeHtml(__('Send')) ?></button>
            </div>
            <div class="attach-icon">
                <label for="file-input">
                    <svg fill="#000000" width="16px" height="16px" viewBox="0 0 35 35" 
                        data-name="Layer 2" id="Layer_2" xmlns="http://www.w3.org/2000/svg" 
                        stroke="#000000" stroke-width="0.00035">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                    <path d="M18,34.75
                        A11.32,11.32,0,0,1,6.69,23.45
                        V8
                        A7.78,7.78,0,0,1,22.25,8
                        V22.49
                        a4.58,4.58,0,1,1-9.15,0
                        V9.29
                        a1.25,1.25,0,0,1,2.5,0
                        v13.2
                        a2.08,2.08,0,1,0,4.15,0
                        V8
                        A5.28,5.28,0,0,0,9.19,8
                        V23.45
                        A8.82,8.82,0,0,0,18,32.25
                        c4.6,0,7.81-3.62,7.81-8.8
                        V9.66
                        a1.25,1.25,0,0,1,2.5,0
                        V23.45
                        C28.31,30,24,34.75,18,34.75Z"
                        stroke="white"
                        stroke-width="1.5"
                        stroke-linecap="round">
                    </path>
                    </g>
                    </svg>
                </label>
                <input type="file" id="file-input" style="display: none;">
            </div>
        </div>
    </div>
</div>

<?php
    $helper = $this->helper('Leeto\TicketLiveChat\Helper\Data');
    $getUsersUrl =  $block->getFullUrl('leeto_support/chat/getusers');
    $updateChatHeaderUrl =  $block->getFullUrl('leeto_support/chat/updatechatheader');
    $updateUnreadChatMessages = $block->getFullUrl('leeto_support/chat/updateunreadmessages');
    $changeChatStatusControllerUrl = $block->getFullUrl('leeto_support/chat/changechatstatus');
    $userAvatarImagePath = $helper->getUserAvatarImagePath();
    $webBaseUrl = substr($helper->getWebBaseUrl(), strpos($helper->getWebBaseUrl(), "//") + 2, -1);
    $webSocketPort = $helper->getWebsocketPort();
?>

<script type="text/x-magento-init">
{
    "#chat-admin-container": { 
        "Leeto_TicketLiveChat/js/chat/list": {
            "getUsersUrl": "<?= $getUsersUrl ?>",
            "updateChatHeaderUrl": "<?= $updateChatHeaderUrl ?>",
            "changeChatStatusControllerUrl": "<?= $changeChatStatusControllerUrl ?>",
            "updateUnreadChatMessages": "<?= $updateUnreadChatMessages ?>",
            "userAvatarImagePath": "<?= $userAvatarImagePath ?>",
            "webBaseUrl": "<?= $webBaseUrl ?>",
            "webSocketPort": "<?= $webSocketPort ?>"
        } 
    }
} 
</script>