<div id="chat-admin-container">
    <div class="user-list-wrapper">
        <div class="chats-info">
            <p>My Chats</p>
            <p>Total Chats: <span class="total-chats"></span></p>
        </div>
        <div class="user-list">
            <!-- List of users goes here -->
        </div>
    </div>
    <h1 class="welcome-message" style="display: none;"></h1>
    <div class="chat-area">
        <div class="chat-header">
            <h2>Chat with <span class="user-name"></span></h2>
        </div>
        <div class="chat-messages">
            <!-- Messages between selected user go here -->
        </div>
        <div class="chat-input">
            <div class="textarea-wrapper">
                <textarea placeholder="Type your message..."></textarea>
                <button>Send</button>
            </div>
            <div class="attach-icon">
                <label for="file-input">
                    <svg fill="#000000" width="16px" height="16px" viewBox="0 0 35 35" data-name="Layer 2" id="Layer_2" xmlns="http://www.w3.org/2000/svg" stroke="#000000" stroke-width="0.00035">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                    <path d="M18,34.75
                        A11.32,11.32,0,0,1,6.69,23.45
                        V8
                        A7.78,7.78,0,0,1,22.25,8
                        V22.49
                        a4.58,4.58,0,1,1-9.15,0
                        V9.29
                        a1.25,1.25,0,0,1,2.5,0
                        v13.2
                        a2.08,2.08,0,1,0,4.15,0
                        V8
                        A5.28,5.28,0,0,0,9.19,8
                        V23.45
                        A8.82,8.82,0,0,0,18,32.25
                        c4.6,0,7.81-3.62,7.81-8.8
                        V9.66
                        a1.25,1.25,0,0,1,2.5,0
                        V23.45
                        C28.31,30,24,34.75,18,34.75Z"
                        stroke="white"
                        stroke-width="1.5"
                        stroke-linecap="round">
                    </path>
                    </g>
                    </svg>
                </label>
                <input type="file" id="file-input" style="display: none;">
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
   "#chat-admin-container": { 
       "Leeto_TicketLiveChat/js/list": {
       } 
   }
} 
</script>