<div id="chat-notify-admin-status" style="display: none;"></div>

<?php
    $helper = $this->helper('Leeto\TicketLiveChat\Helper\Data');
    $webBaseUrl = substr($helper->getWebBaseUrl(), strpos($helper->getWebBaseUrl(), "//") + 2, -1);
    $webSocketPort = $helper->getWebsocketPort();
    $isAdminLoggedIn = $helper->isBackendAdminLoggedIn();
?>
<script type="text/x-magento-init">
{
    "#chat-notify-admin-status": { 
        "Leeto_TicketLiveChat/js/chat/notify-admin-status": {
            "webBaseUrl": "<?= $webBaseUrl ?>",
            "webSocketPort": "<?= $webSocketPort ?>",
            "isAdminLoggedIn": "<?= $isAdminLoggedIn ?>"
        } 
    }
} 
</script>