<div id="chat-notify-admin-status" style="display: none;"></div>

<?php
    $helper = $this->helper(Leeto\TicketLiveChat\Helper\Data::class);
    $webBaseUrl = substr($helper->getWebBaseUrl(), strpos($helper->getWebBaseUrl(), "//") + 2, -1);
    $webSocketPort = $helper->getWebsocketPort();
    $isAdminLoggedIn = $helper->isBackendAdminLoggedIn();
    $chatUnreadMessagesUrl = $helper->getBackendUrl('leeto_support/chat/unreadmessages');
?>
<script type="text/x-magento-init">
{
    "#chat-notify-admin-status": { 
        "Leeto_TicketLiveChat/js/chat/notify-admin-status": {
            "webBaseUrl": "<?= $escaper->escapeHtml($webBaseUrl) ?>",
            "webSocketPort": "<?= $escaper->escapeHtml($webSocketPort) ?>",
            "isAdminLoggedIn": "<?= $escaper->escapeHtml($isAdminLoggedIn) ?>",
            "chatUnreadMessagesUrl": "<?= $escaper->escapeHtml($chatUnreadMessagesUrl) ?>"
        } 
    }
} 
</script>