<div id="status-update-modal">
    <div class="modal-inner-wrapper">
        <div class="modal-content">
            <p><?= $escaper->escapeHtml(__('Are you sure you want to update the status? Ticket will be created.')) ?></p>
            <div class="modal-actions">
                <button id="modalYesBtn" class="action-primary">
                    <span><?= $escaper->escapeHtml(__('Yes')) ?></span>
                </button>
                <button class="action-secondary" id="modalNoBtn">
                    <span><?= $escaper->escapeHtml(__('No')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
