<?php
$ticket = $this->getTicket();
$messages = $this->getTicketMessages();
?>
<div id="ticket-user-container" data-ticket-id="<?= $escaper->escapeHTML($ticket->getId()) ?>">
    <div class="loading-container">
        <div class="loading-circle"></div>
    </div>
    <div class="chat-area">
        <div class="chat-header">
            <div class="left-info">
                <div class="ticket-type">
                    <span class="title"></span>
                    <span class="order-link-wrapper"><a target="_blank" href="" class="order-link"></a></span>
                    <br>
                </div>
                <div class="ticket-subject">
                    <span class="title"><?= $escaper->escapeHtml(__('Subject:')) ?></span>
                    <span class="subject"></span>
                </div>
            </div>
            <div class="right-info">
                <div class="ticket-date">
                    <span class="title"><?= $escaper->escapeHtml(__('Created at:')) ?></span>
                    <span class="date"></span>
                </div>
                <div class="ticket-status">
                    <span class="title"><?= $escaper->escapeHtml(__('Status:')) ?></span>
                </div>
            </div>
        </div>
        <div class="chat-messages">
            <?php foreach ($messages as $message): ?>
                <?php if (isset($message['alertMessage'])): ?>
                    <div class="alert-message info"><?= $escaper->escapeHtml($message['alertMessage']) ?></div>
                <?php else: ?>
                    <div class="ticket-message">
                        <div class="dropdown-item">
                            <div class="icon">
                                <div class="avatar">
                                    <img src="<?= $escaper->escapeHtml($this->getDefaultImage()) ?>" alt="User Image">
                                </div>
                            </div>
                            <?php
                                $from = $message['sender'] == 'admin' ? 'admin' : $ticket->getEmail();
                                $to = $message['sender'] == 'user' ? 'admin' : $ticket->getEmail();
                            ?>
                            <div class="details">
                                <div class="from"><?= $escaper->escapeHtml($from) ?></div>
                                <div class="subject"><?= $escaper->escapeHtml($ticket->getSubject()) ?></div>
                            </div>
                        </div>
                        <div class="detailed-info">
                            <div class="from"><?= $escaper->escapeHtml(__("From:" . $from)) ?></div>
                            <div class="to"><?= $escaper->escapeHtml(__("To:" . $to)) ?></div>
                            <?php if ($message['message']): ?>
                                <div class="message"><?= $escaper->escapeHtml($message['message']) ?></div>
                            <?php endif; ?>
                            <?php if ($message['files']): ?>
                                <div class="files">
                                    <?php foreach ($message['files'] as $file): ?>
                                        <div class="file-content">
                                            <?php if ($file['type'] == 'image'): ?>
                                                <a class="file-image" target="_blank" 
                                                    href="<?= $escaper->escapeHtml($file['path']) ?>">
                                                    <p 
                                                        class="file-name"
                                                    ><?= $escaper->escapeHtml($file['original_name']) ?></p>
                                                    <img src="<?= $escaper->escapeHtml($file['path']) ?>" class="image">
                                                </a>
                                            <?php elseif ($file['type'] == 'file'): ?>
                                                <a href="<?= $escaper->escapeHtml($file['path']) ?>" 
                                                    class="file-name"
                                                    download="<?= $escaper->escapeHtml($file['path']) ?>"
                                                ><?= $escaper->escapeHtml($file['original_name']) ?></a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <div class="chat-input">
            <div class="textarea-wrapper">
                <textarea placeholder="Type your message..."></textarea>
                <button>Send</button>
            </div>
            <div class="attach-icon">
                <label for="user-file-input">
                    <svg fill="#000000" 
                        width="16px" 
                        height="16px" 
                        viewBox="0 0 35 35" 
                        data-name="Layer 2" 
                        id="Layer_2" 
                        xmlns="http://www.w3.org/2000/svg" 
                        stroke="#000000" 
                        stroke-width="0.00035"
                    >
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                    <path d="M18,34.75
                        A11.32,11.32,0,0,1,6.69,23.45
                        V8
                        A7.78,7.78,0,0,1,22.25,8
                        V22.49
                        a4.58,4.58,0,1,1-9.15,0
                        V9.29
                        a1.25,1.25,0,0,1,2.5,0
                        v13.2
                        a2.08,2.08,0,1,0,4.15,0
                        V8
                        A5.28,5.28,0,0,0,9.19,8
                        V23.45
                        A8.82,8.82,0,0,0,18,32.25
                        c4.6,0,7.81-3.62,7.81-8.8
                        V9.66
                        a1.25,1.25,0,0,1,2.5,0
                        V23.45
                        C28.31,30,24,34.75,18,34.75Z"
                        stroke="white"
                        stroke-width="1.5"
                        stroke-linecap="round">
                    </path>
                    </g>
                    </svg>
                </label>
                <input type="file" 
                    id="user-file-input" name="attachments[]" 
                    style="display: none;" accept=".jpg, .jpeg, .png, .pdf, .doc, .docx" multiple>
                <div class="uploaded-files">
                    <div id="uploaded-file-names">
                        <?= $this->escapeHtml(__('Uploaded Files:')) ?> 
                        <span id="uploaded-files-list"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
   "#ticket-user-container": { 
        "Leeto_TicketLiveChat/js/user_ticket": {
            "ticketControllerUrl": "<?= $escaper->escapeHtml($this->getTicketControllerUrl()) ?>",
            "messageControllerUrl": "<?= $escaper->escapeHtml($this->getMessageControllerUrl()) ?>",
            "addAdminMessageControllerUrl": "<?= $escaper->escapeHtml($this->getAddMessageControllerUrl()) ?>",
            "openTicketStatusUrl": "<?= $escaper->escapeHtml($this->getOpenTicketStatusUrl()) ?>"
        } 
   }
} 
</script>